### ISSUE TITLE
New documentation using readthedocs 

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/edu#25]
Dear @prvst @bebatut  @tfursten @dbready @andreas-wilm @Maryom @bgruening @jduckles @delirehberi @cgirardot @starpharm @mr-c : 

First of all thanks for your contribution to BioContainers Documentation. We recently move the documentation from Jekyll to Readthedocs which makes the documentation cleaner and easy to deploy (see the results here - https://biocontainers-edu.readthedocs.io/en/latest/ - ). You can contribute now by adding new sessions in the `read_docs` branch and the docs folder.

Some topics still are missing in the documentation if you would like to contribute: 

- BioContainers and CWL. 
- BioContainers and python notebooks.

**Comment by prvst** [comment]
can we remove the advertisement banners  ?

**Comment by ypriverol** [comment]
Unfortunately, no for now. I’ll check if we can pay for the pro version to avoid the ads.

**Comment by ypriverol** [comment]
We probably need to include a section for multi-tools containers. Can you @bgruening contribute?

**Comment by ypriverol** [comment]
@prvst and @oliver would be great if we can update the best practices to specified for example why we are not using anymore latest tag.

**Comment by bgruening** [comment]
Yes, but not soon. I will put this on our list ...
