### ISSUE TITLE
How to use the singularity links?

### ISSUE THREAD

**Issue by fa2k** [BioContainers/edu#39]
It would be great to have a simple example of how to use the singularity images. I am puzzled about what to do with the https link.

I think something like this example could be helpful to many users.
```
wget  https://depot.galaxyproject.org/singularity/multiqc:1.9--pyh9f0ad1d_0
chmod +x multiqc\:1.9--pyh9f0ad1d_0
./multiqc\:1.9--pyh9f0ad1d_0
```
(this doesn't work for me, so as a first step, would be good to see if I'm doing it wrong)

**Comment by bgruening** [comment]
You need to run the images with singulariy. E.g. `singularity run`

**Comment by fa2k** [comment]
Thanks for the quick reply. So, would this be a valid way to do it?
```
wget  https://depot.galaxyproject.org/singularity/multiqc:1.9--pyh9f0ad1d_0
# Creates a file called "multiqc:1.9--pyh9f0ad1d_0"

singularity run multiqc\:1.9--pyh9f0ad1d_0
```

I get errors like this:
```
ERROR  : Unknown image format/type: multiqc:1.9--pyh9f0ad1d_0
ABORT  : Retval = 255
```
There could be something with my singularity version, but just want to make absolutely sure.

**Comment by fa2k** [comment]
I don't know if you changed anything, or I was just bad at looking before, but the usage links work fine for me now. E.g. here: https://biocontainers.pro/#/tools/multiqc . 

singularity run https://depot.galaxyproject.org/singularity/multiqc:1.9--pyh9f0ad1d_0
